apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.currency.host }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.currency.host }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      http:
        http1MaxPendingRequests: {{ .Values.resilience.maxPendingRequests }}
        maxRequestsPerConnection: {{ .Values.resilience.maxRequestsPerConnection }}
    outlierDetection:
      consecutive5xxErrors: {{ .Values.resilience.consecutive5xxErrors }}
      interval: {{ .Values.resilience.interval }}
      baseEjectionTime: {{ .Values.resilience.baseEjectionTime }}
