apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.currency.host }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.currency.appLabel }}
  rules:
    - from:
        - source:
            principals:
              - {{ .Values.security.walletPrincipal }}
