apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: muffin-wallet
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.ingress.host }}
  gateways:
    - {{ .Values.ingress.gateway }}
  http:
    - route:
        - destination:
            host: muffin-wallet
            port:
              number: {{ .Values.wallet.servicePort }}
