apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: wallet-to-currency
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.currency.host }}
  http:
    - retries:
        attempts: {{ .Values.resilience.retries }}
        perTryTimeout: {{ .Values.resilience.perTryTimeout }}
      timeout: {{ .Values.resilience.timeout }}
      route:
        - destination:
            host: {{ .Values.currency.host }}
            port:
              number: {{ .Values.currency.port }}
