apiVersion: v1
kind: Service
metadata:
  name: muffin-wallet
spec:
  type: {{ .Values.service.type }}
  selector:
    app: muffin-wallet
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}